### ISSUE TITLE
[Lethal Company/Herobrine/V50] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by CoolLKKPS** [ChrisFeline/Mod-Beta-Testing#1]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TMPro.MaterialReference..ctor (System.Int32 index, TMPro.TMP_FontAsset fontAsset, TMPro.TMP_SpriteAsset spriteAsset, UnityEngine.Material material, System.Single padding) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_001D)
TMPro.TextMeshPro.SetArraySizes (TMPro.TMP_Text+UnicodeChar[] unicodeChars) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_0083)
TMPro.TMP_Text.ParseInputText () (at <9baa8119dbcd498f902c1a92f10843c1>:IL_004C)
TMPro.TMP_Text.GetPreferredValues (System.Single width, System.Single height) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_0007)
TMPro.TextMeshPro.Rebuild (UnityEngine.UI.CanvasUpdate update) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_0015)
TMPro.TMP_UpdateManager.DoRebuilds () (at <9baa8119dbcd498f902c1a92f10843c1>:IL_0037)
UnityEngine.Canvas.SendWillRenderCanvases () (at <c6e732ee43764427b2b923952ecc7fa9>:IL_000A)

@ChrisFeline i only can find this way to contact u
when player killed by herobrine, this log will spam in the log console

**Comment by ChrisFeline** [comment]
None of this errors are related to Herobrine.

**Comment by CoolLKKPS** [comment]
weird, only happen when player killed by herobrine, idk

**Comment by ChrisFeline** [comment]
I will take a look

**Comment by CoolLKKPS** [comment]
@ChrisFeline another issue about don't touch me mod, Error while launching the game with that mod, in new V50

**Comment by CoolLKKPS** [comment]
fixed
