### ISSUE TITLE
[LC v68] will cause console error log spaming when Herobrine kill the player, error more related to terminal

### ISSUE THREAD

**Issue by CoolLKKPS** [ChrisFeline/Mod-Beta-Testing#2]
same as topic

**Comment by ChrisFeline** [comment]
I think v55 is still in beta, If I upload an updated compatibility patch it will break things for the stable version of the game.
I will have a look anyway, thank you for the quick update.

**Comment by CoolLKKPS** [comment]
@ChrisFeline if u have time, LC Herobrine still have problem

**Comment by ChrisFeline** [comment]
Released an update

**Comment by CoolLKKPS** [comment]
will test soon
